### ISSUE TITLE
请问如何自己添加新的表情呢？

### ISSUE THREAD

**Issue by zsq1314** [xfgryujk/memegen#2]
你好，请问如何自己添加新的表情呢？自定义添加放入空的gif和配置json会发现生成的表情图片变慢了很多，不清楚自定义添加流程和应该注意些什么？

**Comment by xfgryujk** [comment]
在`src/settings.js`修改模板URL
在`src/templateList.json`添加模板名
在`static/templates`添加新模板

**Comment by zsq1314** [comment]
谢谢，调试了下发现网上下载的gif图片，取delay的值为0，导致添加文字和生成图片的时候这块逻辑有问题，目前加了判断处理，为0设置初始值规避了。不知道为啥读取图片的delay数据没有
